name: CI

on: [push, pull_request]

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_STAGE_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/somnoynadno/services/hack-change-api
            git fetch --all
            git reset --hard origin/master
            cd ..
            docker-compose up --build -d --no-deps invest-api